name: jwst-gtvt-3.9

channels:
  - conda-forge
  - defaults

dependencies:
  - astropy=5.2.2
  - docopt=0.6.2
  - matplotlib=3.7.1
  - numpy=1.24.3
  - pip=23.0
  - pandas=2.0.1
  - python=3.9.16
  - tabulate=0.9.0

  - pip:
    - astroquery==0.4.6
    - pysiaf==0.19.0


    # Current package
    - -e .